config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, presence: true,
                      length: {maximum: 140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(permitted_parameter)
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end
  private
  def permitted_parameter
    params.require(:blog).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/index.html.haml
%h1 Blogs#index
%p Find me in app/views/blogs/index.html.erb
= link_to '新しく投稿する', new_blog_path
%br/
- @blogs.each do |blog|
  = blog.content
  %p
    (#{blog.created_at.strftime("%Y/%m/%d %H:%M")})
  %p

app/views/blogs/new.html.haml
%h1 Blogs#new
%p Find me in app/views/blogs/new.html.erb
= form_with(model: @blog, local: true, url: blogs_path) do |b|
  = b.label :投稿内容
  %br/
  = b.text_area :content
  %br/
  = b.submit :投稿する
= link_to "戻る", blogs_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MiniBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield